-- Migration: Add AI Project Generator fields to projects table
-- Date: 2026-06-15
-- Description: Add fields for AI-generated projects feature

-- Add new columns to projects table
ALTER TABLE projects
ADD COLUMN IF NOT EXISTS project_goal TEXT,
ADD COLUMN IF NOT EXISTS team_size INTEGER,
ADD COLUMN IF NOT EXISTS deadline TEXT,
ADD COLUMN IF NOT EXISTS generated_by_ai BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS project_context TEXT;

-- Create index for AI-generated projects
CREATE INDEX IF NOT EXISTS idx_projects_generated_by_ai ON projects(generated_by_ai);

-- Add comments for documentation
COMMENT ON COLUMN projects.project_goal IS 'Main goal or objective of the project provided by user or AI';
COMMENT ON COLUMN projects.team_size IS 'Expected team size for the project';
COMMENT ON COLUMN projects.deadline IS 'Project deadline (ISO 8601 format)';
COMMENT ON COLUMN projects.generated_by_ai IS 'Whether this project was generated by AI assistant';
COMMENT ON COLUMN projects.project_context IS 'Additional context about the project used for AI generation';

-- Update RLS policies if needed (ensure AI fields are accessible)
-- The existing RLS policies should already cover these new fields
